/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package exampleproject;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.awt.Color;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Bharatha Sachintha
 */
public class availible extends javax.swing.JFrame {
String id;
String available;
    /**
     * Creates new form availible
     */
    public availible() {
        initComponents();
        jPanel1.setBackground(new Color(0,0,0,200));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnexit = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        bb1na = new javax.swing.JRadioButton();
        bb1a = new javax.swing.JRadioButton();
        bb2na = new javax.swing.JRadioButton();
        bb2a = new javax.swing.JRadioButton();
        bb3na = new javax.swing.JRadioButton();
        bb3a = new javax.swing.JRadioButton();
        bb4a = new javax.swing.JRadioButton();
        bb4na = new javax.swing.JRadioButton();
        bb5a = new javax.swing.JRadioButton();
        bb5na = new javax.swing.JRadioButton();
        bb12a = new javax.swing.JRadioButton();
        bb12na = new javax.swing.JRadioButton();
        bb6a = new javax.swing.JRadioButton();
        bb6na = new javax.swing.JRadioButton();
        bb11a = new javax.swing.JRadioButton();
        bb11na = new javax.swing.JRadioButton();
        bb10na = new javax.swing.JRadioButton();
        bb10a = new javax.swing.JRadioButton();
        bb9a = new javax.swing.JRadioButton();
        bb9na = new javax.swing.JRadioButton();
        bb8a = new javax.swing.JRadioButton();
        bb8na = new javax.swing.JRadioButton();
        bb7na = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        bb7a = new javax.swing.JRadioButton();
        txt_date = new com.toedter.calendar.JDateChooser();
        jLabel32 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Vivaldi", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setText("Hogwats Pizza Available Details");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, -1, -1));

        btnexit.setBackground(new java.awt.Color(51, 255, 51));
        btnexit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnexit.setText("Home");
        btnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexitActionPerformed(evt);
            }
        });
        jPanel1.add(btnexit, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 30, 110, 40));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Bharatha Sachintha\\Downloads\\6a-300x300.png")); // NOI18N
        jLabel4.setText("jLabel1");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 0, 150, 130));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Bharatha Sachintha\\Downloads\\12a-300x300.png")); // NOI18N
        jLabel2.setText("jLabel1");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 260, 150, 130));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Bharatha Sachintha\\Downloads\\3a-300x300.png")); // NOI18N
        jLabel5.setText("jLabel1");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 150, 130));

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Bharatha Sachintha\\Downloads\\4a-300x300.png")); // NOI18N
        jLabel6.setText("jLabel1");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 0, 150, 130));

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\Bharatha Sachintha\\Downloads\\1a.png")); // NOI18N
        jLabel7.setText("jLabel1");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, 150, 130));

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\Bharatha Sachintha\\Downloads\\7a-300x300.png")); // NOI18N
        jLabel8.setText("jLabel1");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 150, 130));

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\Bharatha Sachintha\\Downloads\\8a-300x300.png")); // NOI18N
        jLabel9.setText("jLabel1");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 150, 130));

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\Bharatha Sachintha\\Downloads\\9a-300x300.png")); // NOI18N
        jLabel10.setText("jLabel1");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 260, 150, 130));

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\Bharatha Sachintha\\Downloads\\10a-300x300.png")); // NOI18N
        jLabel11.setText("jLabel1");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 260, 150, 130));

        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Users\\Bharatha Sachintha\\Downloads\\11a-300x300.png")); // NOI18N
        jLabel12.setText("jLabel1");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 260, 150, 130));

        jLabel13.setIcon(new javax.swing.ImageIcon("C:\\Users\\Bharatha Sachintha\\Downloads\\5a-300x300.png")); // NOI18N
        jLabel13.setText("jLabel1");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 0, 150, 130));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 51));
        jLabel14.setText("BB6");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 140, 60, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 51));
        jLabel15.setText("BB1");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 60, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 51));
        jLabel16.setText("BB7");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, 60, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 51));
        jLabel17.setText("BB8");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 390, 60, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 51));
        jLabel18.setText("BB9");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 390, 60, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 51));
        jLabel19.setText("BB10");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 390, 60, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 51));
        jLabel20.setText("BB12");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 390, 60, -1));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 51));
        jLabel23.setText("BB2");
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 60, -1));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 51));
        jLabel24.setText("BB3");
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 144, 60, 10));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 51));
        jLabel25.setText("BB4");
        jPanel2.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 140, 60, -1));

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 51));
        jLabel26.setText("BB5");
        jPanel2.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 140, 60, -1));

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 51));
        jLabel27.setText("BB11");
        jPanel2.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 390, 60, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Bharatha Sachintha\\Downloads\\2a-300x300.png")); // NOI18N
        jLabel3.setText("jLabel1");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 150, 130));

        bb1na.setBackground(new java.awt.Color(204, 204, 204));
        bb1na.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bb1na.setForeground(new java.awt.Color(255, 255, 51));
        bb1na.setText("Not Available");
        jPanel2.add(bb1na, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        bb1a.setBackground(new java.awt.Color(204, 204, 204));
        bb1a.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bb1a.setForeground(new java.awt.Color(255, 255, 51));
        bb1a.setText("Available");
        jPanel2.add(bb1a, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        bb2na.setBackground(new java.awt.Color(204, 204, 204));
        bb2na.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bb2na.setForeground(new java.awt.Color(255, 255, 51));
        bb2na.setText("Not Available");
        jPanel2.add(bb2na, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, -1, -1));

        bb2a.setBackground(new java.awt.Color(204, 204, 204));
        bb2a.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bb2a.setForeground(new java.awt.Color(255, 255, 51));
        bb2a.setText("Available");
        jPanel2.add(bb2a, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, -1, -1));

        bb3na.setBackground(new java.awt.Color(204, 204, 204));
        bb3na.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bb3na.setForeground(new java.awt.Color(255, 255, 51));
        bb3na.setText("Not Available");
        jPanel2.add(bb3na, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, -1, -1));

        bb3a.setBackground(new java.awt.Color(204, 204, 204));
        bb3a.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bb3a.setForeground(new java.awt.Color(255, 255, 51));
        bb3a.setText("Available");
        jPanel2.add(bb3a, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 160, -1, -1));

        bb4a.setBackground(new java.awt.Color(204, 204, 204));
        bb4a.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bb4a.setForeground(new java.awt.Color(255, 255, 51));
        bb4a.setText("Available");
        jPanel2.add(bb4a, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 160, -1, -1));

        bb4na.setBackground(new java.awt.Color(204, 204, 204));
        bb4na.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bb4na.setForeground(new java.awt.Color(255, 255, 51));
        bb4na.setText("Not Available");
        jPanel2.add(bb4na, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 190, -1, -1));

        bb5a.setBackground(new java.awt.Color(204, 204, 204));
        bb5a.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bb5a.setForeground(new java.awt.Color(255, 255, 51));
        bb5a.setText("Available");
        jPanel2.add(bb5a, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 160, -1, -1));

        bb5na.setBackground(new java.awt.Color(204, 204, 204));
        bb5na.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bb5na.setForeground(new java.awt.Color(255, 255, 51));
        bb5na.setText("Not Available");
        jPanel2.add(bb5na, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 190, -1, -1));

        bb12a.setBackground(new java.awt.Color(204, 204, 204));
        bb12a.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bb12a.setForeground(new java.awt.Color(255, 255, 51));
        bb12a.setText("Available");
        jPanel2.add(bb12a, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 410, -1, -1));

        bb12na.setBackground(new java.awt.Color(204, 204, 204));
        bb12na.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bb12na.setForeground(new java.awt.Color(255, 255, 51));
        bb12na.setText("Not Available");
        jPanel2.add(bb12na, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 440, -1, -1));

        bb6a.setBackground(new java.awt.Color(204, 204, 204));
        bb6a.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bb6a.setForeground(new java.awt.Color(255, 255, 51));
        bb6a.setText("Available");
        jPanel2.add(bb6a, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 160, -1, -1));

        bb6na.setBackground(new java.awt.Color(204, 204, 204));
        bb6na.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bb6na.setForeground(new java.awt.Color(255, 255, 51));
        bb6na.setText("Not Available");
        jPanel2.add(bb6na, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 190, -1, -1));

        bb11a.setBackground(new java.awt.Color(204, 204, 204));
        bb11a.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bb11a.setForeground(new java.awt.Color(255, 255, 51));
        bb11a.setText("Available");
        jPanel2.add(bb11a, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 410, -1, -1));

        bb11na.setBackground(new java.awt.Color(204, 204, 204));
        bb11na.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bb11na.setForeground(new java.awt.Color(255, 255, 51));
        bb11na.setText("Not Available");
        jPanel2.add(bb11na, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 440, -1, -1));

        bb10na.setBackground(new java.awt.Color(204, 204, 204));
        bb10na.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bb10na.setForeground(new java.awt.Color(255, 255, 51));
        bb10na.setText("Not Available");
        jPanel2.add(bb10na, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 440, -1, -1));

        bb10a.setBackground(new java.awt.Color(204, 204, 204));
        bb10a.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bb10a.setForeground(new java.awt.Color(255, 255, 51));
        bb10a.setText("Available");
        jPanel2.add(bb10a, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 410, -1, -1));

        bb9a.setBackground(new java.awt.Color(204, 204, 204));
        bb9a.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bb9a.setForeground(new java.awt.Color(255, 255, 51));
        bb9a.setText("Available");
        jPanel2.add(bb9a, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 410, 80, -1));

        bb9na.setBackground(new java.awt.Color(204, 204, 204));
        bb9na.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bb9na.setForeground(new java.awt.Color(255, 255, 51));
        bb9na.setText("Not Available");
        jPanel2.add(bb9na, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 440, 110, -1));

        bb8a.setBackground(new java.awt.Color(204, 204, 204));
        bb8a.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bb8a.setForeground(new java.awt.Color(255, 255, 51));
        bb8a.setText("Available");
        jPanel2.add(bb8a, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 410, 80, -1));

        bb8na.setBackground(new java.awt.Color(204, 204, 204));
        bb8na.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bb8na.setForeground(new java.awt.Color(255, 255, 51));
        bb8na.setText("Not Available");
        jPanel2.add(bb8na, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 440, 110, -1));

        bb7na.setBackground(new java.awt.Color(204, 204, 204));
        bb7na.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bb7na.setForeground(new java.awt.Color(255, 255, 51));
        bb7na.setText("Not Available");
        jPanel2.add(bb7na, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 110, -1));

        jButton1.setBackground(new java.awt.Color(102, 255, 102));
        jButton1.setFont(new java.awt.Font("Source Sans Pro Semibold", 1, 18)); // NOI18N
        jButton1.setText("Add Details");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 470, 130, 30));

        jButton2.setBackground(new java.awt.Color(102, 255, 102));
        jButton2.setFont(new java.awt.Font("Source Sans Pro Semibold", 1, 18)); // NOI18N
        jButton2.setText("Add Details");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 130, 30));

        jButton3.setBackground(new java.awt.Color(102, 255, 102));
        jButton3.setFont(new java.awt.Font("Source Sans Pro Semibold", 1, 18)); // NOI18N
        jButton3.setText("Add Details");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 130, 30));

        jButton4.setBackground(new java.awt.Color(102, 255, 102));
        jButton4.setFont(new java.awt.Font("Source Sans Pro Semibold", 1, 18)); // NOI18N
        jButton4.setText("Add Details");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 220, 130, 30));

        jButton5.setBackground(new java.awt.Color(102, 255, 102));
        jButton5.setFont(new java.awt.Font("Source Sans Pro Semibold", 1, 18)); // NOI18N
        jButton5.setText("Add Details");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 220, 130, 30));

        jButton6.setBackground(new java.awt.Color(102, 255, 102));
        jButton6.setFont(new java.awt.Font("Source Sans Pro Semibold", 1, 18)); // NOI18N
        jButton6.setText("Add Details");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 220, 130, 30));

        jButton7.setBackground(new java.awt.Color(102, 255, 102));
        jButton7.setFont(new java.awt.Font("Source Sans Pro Semibold", 1, 18)); // NOI18N
        jButton7.setText("Add Details");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 220, 130, 30));

        jButton8.setBackground(new java.awt.Color(102, 255, 102));
        jButton8.setFont(new java.awt.Font("Source Sans Pro Semibold", 1, 18)); // NOI18N
        jButton8.setText("Add Details");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, 130, 30));

        jButton9.setBackground(new java.awt.Color(102, 255, 102));
        jButton9.setFont(new java.awt.Font("Source Sans Pro Semibold", 1, 18)); // NOI18N
        jButton9.setText("Add Details");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 470, 130, 30));

        jButton10.setBackground(new java.awt.Color(102, 255, 102));
        jButton10.setFont(new java.awt.Font("Source Sans Pro Semibold", 1, 18)); // NOI18N
        jButton10.setText("Add Details");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 470, 130, 30));

        jButton11.setBackground(new java.awt.Color(102, 255, 102));
        jButton11.setFont(new java.awt.Font("Source Sans Pro Semibold", 1, 18)); // NOI18N
        jButton11.setText("Add Details");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 470, 130, 30));

        jButton12.setBackground(new java.awt.Color(102, 255, 102));
        jButton12.setFont(new java.awt.Font("Source Sans Pro Semibold", 1, 18)); // NOI18N
        jButton12.setText("Add Details");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 470, 130, 30));

        bb7a.setBackground(new java.awt.Color(204, 204, 204));
        bb7a.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bb7a.setForeground(new java.awt.Color(255, 255, 51));
        bb7a.setText("Available");
        jPanel2.add(bb7a, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 90, -1));

        jScrollPane2.setViewportView(jPanel2);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1100, 510));

        txt_date.setDateFormatString(" yyyy-MM-dd");
        jPanel1.add(txt_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 600, 300, 30));

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 51));
        jLabel32.setText("Choose The Date:");
        jPanel1.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 590, 190, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 1090, 880));

        jLabel21.setIcon(new javax.swing.ImageIcon("C:\\Users\\Bharatha Sachintha\\Downloads\\pic\\bh\\10794+mushroom+pizza.jpg")); // NOI18N
        jLabel21.setText("jLabel21");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, 500, 670));

        jLabel22.setIcon(new javax.swing.ImageIcon("C:\\Users\\Bharatha Sachintha\\Downloads\\pic\\bh\\10785+vegetarian+pizza.jpg")); // NOI18N
        jLabel22.setText("jLabel21");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 680, 90, 180));

        jLabel28.setIcon(new javax.swing.ImageIcon("C:\\Users\\Bharatha Sachintha\\Downloads\\pic\\bh\\10794+mushroom+pizza.jpg")); // NOI18N
        jLabel28.setText("jLabel21");
        getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 0, 140, 690));

        jLabel29.setIcon(new javax.swing.ImageIcon("C:\\Users\\Bharatha Sachintha\\Downloads\\pic\\bh\\10785+vegetarian+pizza.jpg")); // NOI18N
        jLabel29.setText("jLabel21");
        getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 1, 500, 680));

        jLabel30.setIcon(new javax.swing.ImageIcon("C:\\Users\\Bharatha Sachintha\\Downloads\\pic\\bh\\10785+vegetarian+pizza.jpg")); // NOI18N
        jLabel30.setText("jLabel21");
        getContentPane().add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 670, 500, 190));

        jLabel31.setIcon(new javax.swing.ImageIcon("C:\\Users\\Bharatha Sachintha\\Downloads\\pic\\bh\\10785+vegetarian+pizza.jpg")); // NOI18N
        jLabel31.setText("jLabel21");
        getContentPane().add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 670, 500, 190));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexitActionPerformed
        // TODO add your handling code here:
        mpanel m=new mpanel();
        m.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnexitActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/javap","root","");
            String sql="INSERT INTO pizzaav(id,availabile,date) values(?,?,?)";
              PreparedStatement pst=con.prepareStatement(sql);
            if(bb1a.isSelected()){
                 id="BB1";
                 available="Yes";
                 
            }
            if(bb1na.isSelected()){
                id="BB1";
                available="No";
               
            }
            
           pst.setString(1, id);
                  pst.setString(2, available);
           pst.setString(3, ((JTextField)txt_date.getDateEditor().getUiComponent()).getText());
           pst.executeUpdate();
           JOptionPane.showMessageDialog(null, "Data Insert To Record");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/javap","root","");
            String sql="INSERT INTO pizzaav(id,availabile,date) values(?,?,?)";
              PreparedStatement pst=con.prepareStatement(sql);
           
             if(bb2a.isSelected()){
                id="BB2";
                available="Yes";
                
            }
            if(bb2na.isSelected()){
                id="BB2";
                available="No";
               
            }
            
           pst.setString(1, id);
                  pst.setString(2, available);
           pst.setString(3, ((JTextField)txt_date.getDateEditor().getUiComponent()).getText());
           pst.executeUpdate();
           JOptionPane.showMessageDialog(null, "Data Insert To Record");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/javap","root","");
            String sql="INSERT INTO pizzaav(id,availabile,date) values(?,?,?)";
              PreparedStatement pst=con.prepareStatement(sql);
           
              if(bb3a.isSelected()){
                id="BB3";
                available="Yes";
                
            }
            if(bb3na.isSelected()){
                id="BB3";
                available="No";
               
            }
            
           pst.setString(1, id);
                  pst.setString(2, available);
           pst.setString(3, ((JTextField)txt_date.getDateEditor().getUiComponent()).getText());
           pst.executeUpdate();
           JOptionPane.showMessageDialog(null, "Data Insert To Record");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/javap","root","");
            String sql="INSERT INTO pizzaav(id,availabile,date) values(?,?,?)";
              PreparedStatement pst=con.prepareStatement(sql);
           
              if(bb5a.isSelected()){
                id="BB5";
                available="Yes";
            }
            if(bb5na.isSelected()){
                id="BB5";
                available="No";
            }
            
           pst.setString(1, id);
                  pst.setString(2, available);
           pst.setString(3, ((JTextField)txt_date.getDateEditor().getUiComponent()).getText());
           pst.executeUpdate();
           JOptionPane.showMessageDialog(null, "Data Insert To Record");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/javap","root","");
            String sql="INSERT INTO pizzaav(id,availabile,date) values(?,?,?)";
              PreparedStatement pst=con.prepareStatement(sql);
              if(bb6a.isSelected()){
                id="BB6";
                available="Yes";
            }
            if(bb6na.isSelected()){
                id="BB6";
                available="No";
            }
            
           pst.setString(1, id);
                  pst.setString(2, available);
           pst.setString(3, ((JTextField)txt_date.getDateEditor().getUiComponent()).getText());
           pst.executeUpdate();
           JOptionPane.showMessageDialog(null, "Data Insert To Record");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/javap","root","");
            String sql="INSERT INTO pizzaav(id,availabile,date) values(?,?,?)";
              PreparedStatement pst=con.prepareStatement(sql);
           if(bb7a.isSelected()){
                id="BB7";
                available="Yes";
            }
            if(bb7na.isSelected()){
                id="BB7";
                available="No";
            }
             
           pst.setString(1, id);
                  pst.setString(2, available);
           pst.setString(3, ((JTextField)txt_date.getDateEditor().getUiComponent()).getText());
           pst.executeUpdate();
           JOptionPane.showMessageDialog(null, "Data Insert To Record");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/javap","root","");
            String sql="INSERT INTO pizzaav(id,availabile,date) values(?,?,?)";
              PreparedStatement pst=con.prepareStatement(sql);
           if(bb8a.isSelected()){
                id="BB8";
                available="Yes";
            }
            if(bb8na.isSelected()){
                id="BB8";
                available="No";
            }
             
           pst.setString(1, id);
                  pst.setString(2, available);
           pst.setString(3, ((JTextField)txt_date.getDateEditor().getUiComponent()).getText());
           pst.executeUpdate();
           JOptionPane.showMessageDialog(null, "Data Insert To Record");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/javap","root","");
            String sql="INSERT INTO pizzaav(id,availabile,date) values(?,?,?)";
              PreparedStatement pst=con.prepareStatement(sql);
            if(bb1a.isSelected()){
                 id="BB1";
                 available="Yes";
                 
            }
            if(bb1na.isSelected()){
                id="BB1";
                available="No";
               
            }
             if(bb2a.isSelected()){
                id="BB2";
                available="Yes";
                
            }
            if(bb2na.isSelected()){
                id="BB2";
                available="No";
               
            }
              if(bb3a.isSelected()){
                id="BB3";
                available="Yes";
                
            }
            if(bb3na.isSelected()){
                id="BB3";
                available="No";
               
            }
             if(bb4a.isSelected()){
                id="BB4";
                available="Yes";
            }
            if(bb4na.isSelected()){
                id="BB4";
                available="No";
            }
              if(bb5a.isSelected()){
                id="BB5";
                available="Yes";
            }
            if(bb5na.isSelected()){
                id="BB5";
                available="No";
            }
              if(bb6a.isSelected()){
                id="BB6";
                available="Yes";
            }
            if(bb6na.isSelected()){
                id="BB6";
                available="No";
            }
              if(bb7a.isSelected()){
                id="BB7";
                available="Yes";
            }
            if(bb7na.isSelected()){
                id="BB7";
                available="No";
            }
              if(bb8a.isSelected()){
                id="BB8";
                available="Yes";
            }
            if(bb8na.isSelected()){
                id="BB8";
                available="No";
            }
              if(bb9a.isSelected()){
                id="BB9";
                available="Yes";
            }
            if(bb9na.isSelected()){
                id="BB9";
                available="No";
            }
              if(bb10a.isSelected()){
                id="BB10";
                available="Yes";
            }
            if(bb10na.isSelected()){
                id="BB10";
                available="No";
            }
              if(bb11a.isSelected()){
                id="BB11";
                available="Yes";
            }
            if(bb11na.isSelected()){
                id="BB11";
                available="No";
            }
              if(bb12a.isSelected()){
                id="BB12";
                available="Yes";
            }
            if(bb12na.isSelected()){
                id="BB12";
                available="No";
            }
           pst.setString(1, id);
                  pst.setString(2, available);
           pst.setString(3, ((JTextField)txt_date.getDateEditor().getUiComponent()).getText());
           pst.executeUpdate();
           JOptionPane.showMessageDialog(null, "Data Insert To Record");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/javap","root","");
            String sql="INSERT INTO pizzaav(id,availabile,date) values(?,?,?)";
              PreparedStatement pst=con.prepareStatement(sql);
            if(bb9a.isSelected()){
                id="BB9";
                available="Yes";
            }
            if(bb9na.isSelected()){
                id="BB9";
                available="No";
            }
            
           pst.setString(1, id);
                  pst.setString(2, available);
           pst.setString(3, ((JTextField)txt_date.getDateEditor().getUiComponent()).getText());
           pst.executeUpdate();
           JOptionPane.showMessageDialog(null, "Data Insert To Record");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/javap","root","");
            String sql="INSERT INTO pizzaav(id,availabile,date) values(?,?,?)";
              PreparedStatement pst=con.prepareStatement(sql);
           if(bb10a.isSelected()){
                id="BB10";
                available="Yes";
            }
            if(bb10na.isSelected()){
                id="BB10";
                available="No";
            }
             
           pst.setString(1, id);
                  pst.setString(2, available);
           pst.setString(3, ((JTextField)txt_date.getDateEditor().getUiComponent()).getText());
           pst.executeUpdate();
           JOptionPane.showMessageDialog(null, "Data Insert To Record");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/javap","root","");
            String sql="INSERT INTO pizzaav(id,availabile,date) values(?,?,?)";
              PreparedStatement pst=con.prepareStatement(sql);
             if(bb11a.isSelected()){
                id="BB11";
                available="Yes";
            }
            if(bb11na.isSelected()){
                id="BB11";
                available="No";
            }
            
           pst.setString(1, id);
                  pst.setString(2, available);
           pst.setString(3, ((JTextField)txt_date.getDateEditor().getUiComponent()).getText());
           pst.executeUpdate();
           JOptionPane.showMessageDialog(null, "Data Insert To Record");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/javap","root","");
            String sql="INSERT INTO pizzaav(id,availabile,date) values(?,?,?)";
              PreparedStatement pst=con.prepareStatement(sql);
           
              if(bb12a.isSelected()){
                id="BB12";
                available="Yes";
            }
            if(bb12na.isSelected()){
                id="BB12";
                available="No";
            }
           pst.setString(1, id);
                  pst.setString(2, available);
           pst.setString(3, ((JTextField)txt_date.getDateEditor().getUiComponent()).getText());
           pst.executeUpdate();
           JOptionPane.showMessageDialog(null, "Data Insert To Record");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton12ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(availible.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(availible.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(availible.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(availible.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new availible().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton bb10a;
    private javax.swing.JRadioButton bb10na;
    private javax.swing.JRadioButton bb11a;
    private javax.swing.JRadioButton bb11na;
    private javax.swing.JRadioButton bb12a;
    private javax.swing.JRadioButton bb12na;
    private javax.swing.JRadioButton bb1a;
    private javax.swing.JRadioButton bb1na;
    private javax.swing.JRadioButton bb2a;
    private javax.swing.JRadioButton bb2na;
    private javax.swing.JRadioButton bb3a;
    private javax.swing.JRadioButton bb3na;
    private javax.swing.JRadioButton bb4a;
    private javax.swing.JRadioButton bb4na;
    private javax.swing.JRadioButton bb5a;
    private javax.swing.JRadioButton bb5na;
    private javax.swing.JRadioButton bb6a;
    private javax.swing.JRadioButton bb6na;
    private javax.swing.JRadioButton bb7a;
    private javax.swing.JRadioButton bb7na;
    private javax.swing.JRadioButton bb8a;
    private javax.swing.JRadioButton bb8na;
    private javax.swing.JRadioButton bb9a;
    private javax.swing.JRadioButton bb9na;
    private javax.swing.JButton btnexit;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private com.toedter.calendar.JDateChooser txt_date;
    // End of variables declaration//GEN-END:variables
}
