/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package exampleproject;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
//import com.teknikindustries.bulksms.SMS;

/**
 *
 * @author Bharatha Sachintha
 */
public class lastbill extends javax.swing.JFrame {

    /**
     * Creates new form lastbill
     */
    public lastbill() {
        initComponents();
        jPanel1.setBackground(new Color(0,0,0,200));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jButton14 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtsearchbill = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        txt_data = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        txtitem = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtsearch = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtaddress = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtphone = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        bb1l = new javax.swing.JRadioButton();
        bb1s = new javax.swing.JRadioButton();
        bb1m = new javax.swing.JRadioButton();
        bb2s = new javax.swing.JRadioButton();
        bb2m = new javax.swing.JRadioButton();
        bb2l = new javax.swing.JRadioButton();
        bb3m = new javax.swing.JRadioButton();
        bb3s = new javax.swing.JRadioButton();
        bb3l = new javax.swing.JRadioButton();
        bb4l = new javax.swing.JRadioButton();
        bb4m = new javax.swing.JRadioButton();
        bb4s = new javax.swing.JRadioButton();
        bb5s = new javax.swing.JRadioButton();
        bb5m = new javax.swing.JRadioButton();
        bb5l = new javax.swing.JRadioButton();
        bb6l = new javax.swing.JRadioButton();
        bb6m = new javax.swing.JRadioButton();
        bb6s = new javax.swing.JRadioButton();
        bb7s = new javax.swing.JRadioButton();
        bb7m = new javax.swing.JRadioButton();
        bb7l = new javax.swing.JRadioButton();
        bb8s = new javax.swing.JRadioButton();
        bb8l = new javax.swing.JRadioButton();
        bb8m = new javax.swing.JRadioButton();
        bb9s = new javax.swing.JRadioButton();
        bb9l = new javax.swing.JRadioButton();
        bb9m = new javax.swing.JRadioButton();
        bb10s = new javax.swing.JRadioButton();
        bb10l = new javax.swing.JRadioButton();
        bb10m = new javax.swing.JRadioButton();
        bb11s = new javax.swing.JRadioButton();
        bb11l = new javax.swing.JRadioButton();
        bb11m = new javax.swing.JRadioButton();
        bb12s = new javax.swing.JRadioButton();
        bb12m = new javax.swing.JRadioButton();
        bb12l = new javax.swing.JRadioButton();
        btninsert = new javax.swing.JButton();
        btnb1 = new javax.swing.JButton();
        btnb2 = new javax.swing.JButton();
        btnb3 = new javax.swing.JButton();
        btnb4 = new javax.swing.JButton();
        btnb5 = new javax.swing.JButton();
        btnb6 = new javax.swing.JButton();
        btnb7 = new javax.swing.JButton();
        btnb8 = new javax.swing.JButton();
        btnb9 = new javax.swing.JButton();
        btnb10 = new javax.swing.JButton();
        btnb11 = new javax.swing.JButton();
        txttotal = new javax.swing.JTextField();
        bb1t = new javax.swing.JTextField();
        bb2t = new javax.swing.JTextField();
        bb3t = new javax.swing.JTextField();
        bb4t = new javax.swing.JTextField();
        bb5t = new javax.swing.JTextField();
        bb6t = new javax.swing.JTextField();
        bb7t = new javax.swing.JTextField();
        bb8t = new javax.swing.JTextField();
        bb9t = new javax.swing.JTextField();
        bb10t = new javax.swing.JTextField();
        bb11t = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        bb12t = new javax.swing.JTextField();
        btnb12 = new javax.swing.JButton();
        btnlast = new javax.swing.JButton();
        bb1q = new javax.swing.JTextField();
        bb2q = new javax.swing.JTextField();
        bb3q = new javax.swing.JTextField();
        bb4q = new javax.swing.JTextField();
        bb5q = new javax.swing.JTextField();
        bb6q = new javax.swing.JTextField();
        bb7q = new javax.swing.JTextField();
        bb8q = new javax.swing.JTextField();
        bb9q = new javax.swing.JTextField();
        bb10q = new javax.swing.JTextField();
        bb11q = new javax.swing.JTextField();
        bb12q = new javax.swing.JTextField();
        txttime1 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        txtnum = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel29.setFont(new java.awt.Font("Vivaldi", 1, 48)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(0, 0, 204));
        jLabel29.setText("Hogwarts pizza Final Bill");
        jPanel1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 590, -1));

        jButton14.setBackground(new java.awt.Color(0, 255, 0));
        jButton14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton14.setText("Home");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 40, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 102));
        jLabel3.setText("Search the Bill Number:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 170, -1));

        txtsearchbill.setBackground(new java.awt.Color(153, 255, 153));
        txtsearchbill.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtsearchbill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsearchbillActionPerformed(evt);
            }
        });
        txtsearchbill.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtsearchbillKeyReleased(evt);
            }
        });
        jPanel1.add(txtsearchbill, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 250, -1));

        jLabel34.setBackground(new java.awt.Color(255, 255, 51));
        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 51));
        jLabel34.setText("Date:");
        jPanel1.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jLabel35.setBackground(new java.awt.Color(255, 255, 51));
        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 51));
        jLabel35.setText("Time:");
        jPanel1.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        txt_data.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(txt_data, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 290, -1));

        jLabel30.setBackground(new java.awt.Color(255, 255, 51));
        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 51));
        jLabel30.setText("BB10");
        jPanel1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 410, -1, -1));

        txtitem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(txtitem, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 290, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 204));
        jLabel5.setText(" CUSTOMER DETAILS:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 260, -1));

        txtsearch.setBackground(new java.awt.Color(153, 255, 153));
        txtsearch.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtsearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtsearchKeyReleased(evt);
            }
        });
        jPanel1.add(txtsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, 230, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 0));
        jLabel7.setText("Customer Name:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, -1));

        txtname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 350, 230, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 0));
        jLabel8.setText("Customer Address:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, -1, -1));

        txtaddress.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(txtaddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 390, 230, 40));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 0));
        jLabel9.setText("Total Price:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 570, 90, -1));

        txtphone.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(txtphone, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 450, 230, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 0));
        jLabel11.setText("Search Customer Name:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 170, -1));

        jPanel2.setBackground(new java.awt.Color(255, 0, 0));
        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, -1, 400));

        jPanel3.setBackground(new java.awt.Color(255, 0, 0));
        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 100, 530, -1));

        jLabel31.setBackground(new java.awt.Color(255, 255, 51));
        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 51));
        jLabel31.setText("Selected Items:");
        jPanel1.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        jLabel32.setBackground(new java.awt.Color(255, 255, 51));
        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 51));
        jLabel32.setText("Selected Items:");
        jPanel1.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 120, -1, -1));

        jLabel36.setBackground(new java.awt.Color(255, 255, 51));
        jLabel36.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 51));
        jLabel36.setText("BB1");
        jPanel1.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 140, -1, -1));

        jLabel37.setBackground(new java.awt.Color(255, 255, 51));
        jLabel37.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 255, 51));
        jLabel37.setText("BB2");
        jPanel1.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 170, -1, -1));

        jLabel38.setBackground(new java.awt.Color(255, 255, 51));
        jLabel38.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 51));
        jLabel38.setText("BB3");
        jPanel1.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 200, -1, -1));

        jLabel39.setBackground(new java.awt.Color(255, 255, 51));
        jLabel39.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 255, 51));
        jLabel39.setText("BB4");
        jPanel1.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 230, -1, -1));

        jLabel40.setBackground(new java.awt.Color(255, 255, 51));
        jLabel40.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(255, 255, 51));
        jLabel40.setText("BB5");
        jPanel1.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 260, -1, -1));

        jLabel41.setBackground(new java.awt.Color(255, 255, 51));
        jLabel41.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(255, 255, 51));
        jLabel41.setText("BB6");
        jPanel1.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 290, -1, -1));

        jLabel42.setBackground(new java.awt.Color(255, 255, 51));
        jLabel42.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(255, 255, 51));
        jLabel42.setText("BB7");
        jPanel1.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 320, -1, -1));

        jLabel43.setBackground(new java.awt.Color(255, 255, 51));
        jLabel43.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(255, 255, 51));
        jLabel43.setText("BB8");
        jPanel1.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 350, -1, -1));

        jLabel44.setBackground(new java.awt.Color(255, 255, 51));
        jLabel44.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(255, 255, 51));
        jLabel44.setText("BB12");
        jPanel1.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 470, -1, -1));

        jLabel45.setBackground(new java.awt.Color(255, 255, 51));
        jLabel45.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(255, 255, 51));
        jLabel45.setText("BB9");
        jPanel1.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 380, -1, -1));

        jLabel46.setBackground(new java.awt.Color(255, 255, 51));
        jLabel46.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(255, 255, 51));
        jLabel46.setText("BB11");
        jPanel1.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 440, -1, -1));

        bb1l.setBackground(new java.awt.Color(204, 204, 204));
        bb1l.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bb1l.setForeground(new java.awt.Color(255, 255, 51));
        bb1l.setText("L");
        jPanel1.add(bb1l, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 140, -1, -1));

        bb1s.setBackground(new java.awt.Color(204, 204, 204));
        bb1s.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bb1s.setForeground(new java.awt.Color(255, 255, 51));
        bb1s.setText("S");
        jPanel1.add(bb1s, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 140, -1, -1));

        bb1m.setBackground(new java.awt.Color(204, 204, 204));
        bb1m.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bb1m.setForeground(new java.awt.Color(255, 255, 51));
        bb1m.setText("M");
        jPanel1.add(bb1m, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 140, -1, -1));

        bb2s.setBackground(new java.awt.Color(204, 204, 204));
        bb2s.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bb2s.setForeground(new java.awt.Color(255, 255, 51));
        bb2s.setText("S");
        jPanel1.add(bb2s, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 170, -1, -1));

        bb2m.setBackground(new java.awt.Color(204, 204, 204));
        bb2m.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bb2m.setForeground(new java.awt.Color(255, 255, 51));
        bb2m.setText("M");
        jPanel1.add(bb2m, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 170, -1, -1));

        bb2l.setBackground(new java.awt.Color(204, 204, 204));
        bb2l.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bb2l.setForeground(new java.awt.Color(255, 255, 51));
        bb2l.setText("L");
        jPanel1.add(bb2l, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 170, -1, -1));

        bb3m.setBackground(new java.awt.Color(204, 204, 204));
        bb3m.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bb3m.setForeground(new java.awt.Color(255, 255, 51));
        bb3m.setText("M");
        jPanel1.add(bb3m, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 200, -1, -1));

        bb3s.setBackground(new java.awt.Color(204, 204, 204));
        bb3s.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bb3s.setForeground(new java.awt.Color(255, 255, 51));
        bb3s.setText("S");
        jPanel1.add(bb3s, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 200, -1, -1));

        bb3l.setBackground(new java.awt.Color(204, 204, 204));
        bb3l.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bb3l.setForeground(new java.awt.Color(255, 255, 51));
        bb3l.setText("L");
        jPanel1.add(bb3l, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 200, -1, -1));

        bb4l.setBackground(new java.awt.Color(204, 204, 204));
        bb4l.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bb4l.setForeground(new java.awt.Color(255, 255, 51));
        bb4l.setText("L");
        jPanel1.add(bb4l, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 230, -1, -1));

        bb4m.setBackground(new java.awt.Color(204, 204, 204));
        bb4m.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bb4m.setForeground(new java.awt.Color(255, 255, 51));
        bb4m.setText("M");
        jPanel1.add(bb4m, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 230, -1, -1));

        bb4s.setBackground(new java.awt.Color(204, 204, 204));
        bb4s.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bb4s.setForeground(new java.awt.Color(255, 255, 51));
        bb4s.setText("S");
        jPanel1.add(bb4s, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 230, -1, -1));

        bb5s.setBackground(new java.awt.Color(204, 204, 204));
        bb5s.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bb5s.setForeground(new java.awt.Color(255, 255, 51));
        bb5s.setText("S");
        jPanel1.add(bb5s, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 260, -1, -1));

        bb5m.setBackground(new java.awt.Color(204, 204, 204));
        bb5m.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bb5m.setForeground(new java.awt.Color(255, 255, 51));
        bb5m.setText("M");
        jPanel1.add(bb5m, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 260, -1, -1));

        bb5l.setBackground(new java.awt.Color(204, 204, 204));
        bb5l.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bb5l.setForeground(new java.awt.Color(255, 255, 51));
        bb5l.setText("L");
        jPanel1.add(bb5l, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 260, -1, -1));

        bb6l.setBackground(new java.awt.Color(204, 204, 204));
        bb6l.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bb6l.setForeground(new java.awt.Color(255, 255, 51));
        bb6l.setText("L");
        jPanel1.add(bb6l, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 290, -1, -1));

        bb6m.setBackground(new java.awt.Color(204, 204, 204));
        bb6m.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bb6m.setForeground(new java.awt.Color(255, 255, 51));
        bb6m.setText("M");
        jPanel1.add(bb6m, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 290, -1, -1));

        bb6s.setBackground(new java.awt.Color(204, 204, 204));
        bb6s.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bb6s.setForeground(new java.awt.Color(255, 255, 51));
        bb6s.setText("S");
        jPanel1.add(bb6s, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 290, -1, -1));

        bb7s.setBackground(new java.awt.Color(204, 204, 204));
        bb7s.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bb7s.setForeground(new java.awt.Color(255, 255, 51));
        bb7s.setText("S");
        jPanel1.add(bb7s, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 320, -1, -1));

        bb7m.setBackground(new java.awt.Color(204, 204, 204));
        bb7m.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bb7m.setForeground(new java.awt.Color(255, 255, 51));
        bb7m.setText("M");
        jPanel1.add(bb7m, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 320, -1, -1));

        bb7l.setBackground(new java.awt.Color(204, 204, 204));
        bb7l.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bb7l.setForeground(new java.awt.Color(255, 255, 51));
        bb7l.setText("L");
        jPanel1.add(bb7l, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 320, -1, -1));

        bb8s.setBackground(new java.awt.Color(204, 204, 204));
        bb8s.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bb8s.setForeground(new java.awt.Color(255, 255, 51));
        bb8s.setText("S");
        bb8s.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bb8sActionPerformed(evt);
            }
        });
        jPanel1.add(bb8s, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 350, -1, -1));

        bb8l.setBackground(new java.awt.Color(204, 204, 204));
        bb8l.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bb8l.setForeground(new java.awt.Color(255, 255, 51));
        bb8l.setText("L");
        jPanel1.add(bb8l, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 350, -1, -1));

        bb8m.setBackground(new java.awt.Color(204, 204, 204));
        bb8m.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bb8m.setForeground(new java.awt.Color(255, 255, 51));
        bb8m.setText("M");
        jPanel1.add(bb8m, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 350, -1, -1));

        bb9s.setBackground(new java.awt.Color(204, 204, 204));
        bb9s.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bb9s.setForeground(new java.awt.Color(255, 255, 51));
        bb9s.setText("S");
        jPanel1.add(bb9s, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 380, -1, -1));

        bb9l.setBackground(new java.awt.Color(204, 204, 204));
        bb9l.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bb9l.setForeground(new java.awt.Color(255, 255, 51));
        bb9l.setText("L");
        jPanel1.add(bb9l, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 380, -1, -1));

        bb9m.setBackground(new java.awt.Color(204, 204, 204));
        bb9m.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bb9m.setForeground(new java.awt.Color(255, 255, 51));
        bb9m.setText("M");
        jPanel1.add(bb9m, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 380, -1, -1));

        bb10s.setBackground(new java.awt.Color(204, 204, 204));
        bb10s.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bb10s.setForeground(new java.awt.Color(255, 255, 51));
        bb10s.setText("S");
        jPanel1.add(bb10s, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 410, -1, -1));

        bb10l.setBackground(new java.awt.Color(204, 204, 204));
        bb10l.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bb10l.setForeground(new java.awt.Color(255, 255, 51));
        bb10l.setText("L");
        jPanel1.add(bb10l, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 410, -1, -1));

        bb10m.setBackground(new java.awt.Color(204, 204, 204));
        bb10m.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bb10m.setForeground(new java.awt.Color(255, 255, 51));
        bb10m.setText("M");
        jPanel1.add(bb10m, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 410, -1, -1));

        bb11s.setBackground(new java.awt.Color(204, 204, 204));
        bb11s.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bb11s.setForeground(new java.awt.Color(255, 255, 51));
        bb11s.setText("S");
        jPanel1.add(bb11s, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 440, -1, -1));

        bb11l.setBackground(new java.awt.Color(204, 204, 204));
        bb11l.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bb11l.setForeground(new java.awt.Color(255, 255, 51));
        bb11l.setText("L");
        jPanel1.add(bb11l, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 440, -1, -1));

        bb11m.setBackground(new java.awt.Color(204, 204, 204));
        bb11m.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bb11m.setForeground(new java.awt.Color(255, 255, 51));
        bb11m.setText("M");
        jPanel1.add(bb11m, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 440, -1, -1));

        bb12s.setBackground(new java.awt.Color(204, 204, 204));
        bb12s.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bb12s.setForeground(new java.awt.Color(255, 255, 51));
        bb12s.setText("S");
        jPanel1.add(bb12s, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 470, -1, -1));

        bb12m.setBackground(new java.awt.Color(204, 204, 204));
        bb12m.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bb12m.setForeground(new java.awt.Color(255, 255, 51));
        bb12m.setText("M");
        jPanel1.add(bb12m, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 470, -1, -1));

        bb12l.setBackground(new java.awt.Color(204, 204, 204));
        bb12l.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bb12l.setForeground(new java.awt.Color(255, 255, 51));
        bb12l.setText("L");
        jPanel1.add(bb12l, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 470, -1, -1));

        btninsert.setBackground(new java.awt.Color(153, 255, 153));
        btninsert.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btninsert.setText("Insert Data");
        btninsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btninsertActionPerformed(evt);
            }
        });
        jPanel1.add(btninsert, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, 400, 40));

        btnb1.setBackground(new java.awt.Color(153, 255, 153));
        btnb1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnb1.setText("Get Price");
        btnb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnb1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 140, -1, -1));

        btnb2.setBackground(new java.awt.Color(153, 255, 153));
        btnb2.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnb2.setText("Get Price");
        btnb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnb2ActionPerformed(evt);
            }
        });
        jPanel1.add(btnb2, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 170, -1, -1));

        btnb3.setBackground(new java.awt.Color(153, 255, 153));
        btnb3.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnb3.setText("Get Price");
        btnb3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnb3ActionPerformed(evt);
            }
        });
        jPanel1.add(btnb3, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 200, -1, -1));

        btnb4.setBackground(new java.awt.Color(153, 255, 153));
        btnb4.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnb4.setText("Get Price");
        btnb4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnb4ActionPerformed(evt);
            }
        });
        jPanel1.add(btnb4, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 230, -1, -1));

        btnb5.setBackground(new java.awt.Color(153, 255, 153));
        btnb5.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnb5.setText("Get Price");
        btnb5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnb5ActionPerformed(evt);
            }
        });
        jPanel1.add(btnb5, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 260, -1, -1));

        btnb6.setBackground(new java.awt.Color(153, 255, 153));
        btnb6.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnb6.setText("Get Price");
        btnb6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnb6ActionPerformed(evt);
            }
        });
        jPanel1.add(btnb6, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 290, -1, -1));

        btnb7.setBackground(new java.awt.Color(153, 255, 153));
        btnb7.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnb7.setText("Get Price");
        btnb7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnb7ActionPerformed(evt);
            }
        });
        jPanel1.add(btnb7, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 320, -1, -1));

        btnb8.setBackground(new java.awt.Color(153, 255, 153));
        btnb8.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnb8.setText("Get Price");
        btnb8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnb8ActionPerformed(evt);
            }
        });
        jPanel1.add(btnb8, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 350, -1, -1));

        btnb9.setBackground(new java.awt.Color(153, 255, 153));
        btnb9.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnb9.setText("Get Price");
        btnb9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnb9ActionPerformed(evt);
            }
        });
        jPanel1.add(btnb9, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 380, -1, -1));

        btnb10.setBackground(new java.awt.Color(153, 255, 153));
        btnb10.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnb10.setText("Get Price");
        btnb10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnb10ActionPerformed(evt);
            }
        });
        jPanel1.add(btnb10, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 410, -1, -1));

        btnb11.setBackground(new java.awt.Color(153, 255, 153));
        btnb11.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnb11.setText("Get Price");
        btnb11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnb11ActionPerformed(evt);
            }
        });
        jPanel1.add(btnb11, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 440, -1, -1));

        txttotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel1.add(txttotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 570, 350, -1));

        bb1t.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(bb1t, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 140, 130, -1));

        bb2t.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(bb2t, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 170, 130, -1));

        bb3t.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(bb3t, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 200, 130, -1));

        bb4t.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(bb4t, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 230, 130, -1));

        bb5t.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(bb5t, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 260, 130, -1));

        bb6t.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(bb6t, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 290, 130, -1));

        bb7t.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(bb7t, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 320, 130, -1));

        bb8t.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(bb8t, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 350, 130, -1));

        bb9t.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(bb9t, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 380, 130, -1));

        bb10t.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(bb10t, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 410, 130, 20));

        bb11t.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(bb11t, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 440, 130, -1));

        jPanel4.setBackground(new java.awt.Color(255, 0, 0));
        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 470, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 0));
        jLabel10.setText(" Customer Phone Number:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, -1, -1));

        bb12t.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(bb12t, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 470, 130, -1));

        btnb12.setBackground(new java.awt.Color(153, 255, 153));
        btnb12.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnb12.setText("Get Price");
        btnb12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnb12ActionPerformed(evt);
            }
        });
        jPanel1.add(btnb12, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 470, -1, -1));

        btnlast.setBackground(new java.awt.Color(153, 255, 153));
        btnlast.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnlast.setText("Last Price");
        btnlast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlastActionPerformed(evt);
            }
        });
        jPanel1.add(btnlast, new org.netbeans.lib.awtextra.AbsoluteConstraints(509, 510, 480, 40));

        bb1q.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(bb1q, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 140, 80, -1));

        bb2q.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(bb2q, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 170, 80, -1));

        bb3q.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(bb3q, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 200, 80, -1));

        bb4q.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(bb4q, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 230, 80, -1));

        bb5q.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(bb5q, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 260, 80, -1));

        bb6q.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(bb6q, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 290, 80, -1));

        bb7q.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(bb7q, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 320, 80, -1));

        bb8q.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(bb8q, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 350, 80, -1));

        bb9q.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(bb9q, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 380, 80, -1));

        bb10q.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(bb10q, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 410, 80, 20));

        bb11q.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(bb11q, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 440, 80, -1));

        bb12q.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(bb12q, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 470, 80, -1));

        txttime1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(txttime1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 290, -1));

        jLabel33.setBackground(new java.awt.Color(255, 255, 51));
        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 51));
        jLabel33.setText("Bill Number:");
        jPanel1.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 190, -1));

        txtnum.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(txtnum, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 290, -1));

        jButton1.setBackground(new java.awt.Color(102, 255, 102));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Print Bill");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 600, 400, 40));

        jButton2.setBackground(new java.awt.Color(102, 255, 102));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("Send SMS");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 550, 400, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 660));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Bharatha Sachintha\\Downloads\\pic\\bh\\5489+Almond+cake.jpg")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, -10, 500, 660));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Bharatha Sachintha\\Downloads\\pic\\bh\\5105+Choc+Creme+caramel.jpg")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 500, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
        home rt=new home();
        rt.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton14ActionPerformed

    private void txtsearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsearchKeyReleased
        // TODO add your handling code here:
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/javap","root","");
            String sql="SELECT name,address,phone FROM customer where name=?";
            PreparedStatement pst=con.prepareStatement(sql);
            pst.setString(1,txtsearch.getText());
            ResultSet rs=pst.executeQuery();
            if(rs.next()){
                
                String setname=rs.getString("name");
                txtname.setText(setname);
                String setaddress=rs.getString("address");
                txtaddress.setText(setaddress);
                String setphone=rs.getString("phone");
                txtphone.setText(setphone);
                
            }
            con.close();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_txtsearchKeyReleased

    private void bb8sActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bb8sActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bb8sActionPerformed

    private void btnb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnb1ActionPerformed
        // TODO add your handling code here:
        try{
            double select,qty=0.0,price;
        qty=Double.parseDouble(bb1q.getText());
        if(bb1s.isSelected()){
            select=550.00;
            price=select*qty;
            bb1t.setText(price+"");
        }
        if(bb1m.isSelected()){
            select=850.00;
            price=select*qty;
            bb1t.setText(price+"");
        }
        if(bb1l.isSelected()){
            select=1050.00;
            price=select*qty;
            bb1t.setText(price+"");
        }
        
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        
        
        
    }//GEN-LAST:event_btnb1ActionPerformed

    private void btnb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnb2ActionPerformed
        // TODO add your handling code here:
        double select,qty=0.0,price;
        qty=Double.parseDouble(bb2q.getText());
        if(bb2s.isSelected()){
            select=550.00;
            price=select*qty;
            bb2t.setText(price+"");
        }
        if(bb2m.isSelected()){
            select=850.00;
            price=select*qty;
            bb2t.setText(price+"");
        }
        if(bb2l.isSelected()){
            select=1050.00;
            price=select*qty;
            bb2t.setText(price+"");
        }
    }//GEN-LAST:event_btnb2ActionPerformed

    private void btnb3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnb3ActionPerformed
        // TODO add your handling code here:
        double select,qty=0.0,price;
        qty=Double.parseDouble(bb3q.getText());
        if(bb3s.isSelected()){
            select=550.00;
            price=select*qty;
            bb3t.setText(price+"");
        }
        if(bb3m.isSelected()){
            select=850.00;
            price=select*qty;
            bb3t.setText(price+"");
        }
        if(bb3l.isSelected()){
            select=1050.00;
            price=select*qty;
            bb3t.setText(price+"");
        }
    }//GEN-LAST:event_btnb3ActionPerformed

    private void btnb4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnb4ActionPerformed
        // TODO add your handling code here:
        double select,qty=0.0,price;
        qty=Double.parseDouble(bb4q.getText());
        if(bb4s.isSelected()){
            select=550.00;
            price=select*qty;
            bb4t.setText(price+"");
        }
        if(bb4m.isSelected()){
            select=850.00;
            price=select*qty;
            bb4t.setText(price+"");
        }
        if(bb4l.isSelected()){
            select=1050.00;
            price=select*qty;
            bb4t.setText(price+"");
        }
    }//GEN-LAST:event_btnb4ActionPerformed

    private void btnb5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnb5ActionPerformed
        // TODO add your handling code here:
        double select,qty=0.0,price;
        qty=Double.parseDouble(bb5q.getText());
        if(bb5s.isSelected()){
            select=550.00;
            price=select*qty;
            bb5t.setText(price+"");
        }
        if(bb5m.isSelected()){
            select=850.00;
            price=select*qty;
            bb5t.setText(price+"");
        }
        if(bb5l.isSelected()){
            select=1050.00;
            price=select*qty;
            bb5t.setText(price+"");
        }
    }//GEN-LAST:event_btnb5ActionPerformed

    private void btnb6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnb6ActionPerformed
        // TODO add your handling code here:
        double select,qty=0.0,price;
        qty=Double.parseDouble(bb6q.getText());
        if(bb6s.isSelected()){
            select=550.00;
            price=select*qty;
            bb6t.setText(price+"");
        }
        if(bb6m.isSelected()){
            select=850.00;
            price=select*qty;
            bb6t.setText(price+"");
        }
        if(bb6l.isSelected()){
            select=1050.00;
            price=select*qty;
            bb6t.setText(price+"");
        }
    }//GEN-LAST:event_btnb6ActionPerformed

    private void btnb7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnb7ActionPerformed
        // TODO add your handling code here:
        double select,qty=0.0,price;
        qty=Double.parseDouble(bb7q.getText());
        if(bb7s.isSelected()){
            select=550.00;
            price=select*qty;
            bb7t.setText(price+"");
        }
        if(bb7m.isSelected()){
            select=850.00;
            price=select*qty;
            bb7t.setText(price+"");
        }
        if(bb7l.isSelected()){
            select=1050.00;
            price=select*qty;
            bb7t.setText(price+"");
        }
    }//GEN-LAST:event_btnb7ActionPerformed

    private void btnb8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnb8ActionPerformed
        // TODO add your handling code here:
        double select,qty=0.0,price;
        qty=Double.parseDouble(bb8q.getText());
        if(bb8s.isSelected()){
            select=550.00;
            price=select*qty;
            bb8t.setText(price+"");
        }
        if(bb8m.isSelected()){
            select=850.00;
            price=select*qty;
            bb8t.setText(price+"");
        }
        if(bb8l.isSelected()){
            select=1050.00;
            price=select*qty;
            bb8t.setText(price+"");
        }
    }//GEN-LAST:event_btnb8ActionPerformed

    private void btnb9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnb9ActionPerformed
        // TODO add your handling code here:
        double select,qty=0.0,price;
        qty=Double.parseDouble(bb9q.getText());
        if(bb9s.isSelected()){
            select=550.00;
            price=select*qty;
            bb9t.setText(price+"");
        }
        if(bb9m.isSelected()){
            select=850.00;
            price=select*qty;
            bb9t.setText(price+"");
        }
        if(bb9l.isSelected()){
            select=1050.00;
            price=select*qty;
            bb9t.setText(price+"");
        }
    }//GEN-LAST:event_btnb9ActionPerformed

    private void btnb10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnb10ActionPerformed
        // TODO add your handling code here:
        double select,qty=0.0,price;
        qty=Double.parseDouble(bb10q.getText());
        if(bb10s.isSelected()){
            select=550.00;
            price=select*qty;
            bb10t.setText(price+"");
        }
        if(bb10m.isSelected()){
            select=850.00;
            price=select*qty;
            bb10t.setText(price+"");
        }
        if(bb10l.isSelected()){
            select=1050.00;
            price=select*qty;
            bb10t.setText(price+"");
        }
    }//GEN-LAST:event_btnb10ActionPerformed

    private void btnb11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnb11ActionPerformed
        // TODO add your handling code here:
        double select,qty=0.0,price;
        qty=Double.parseDouble(bb11q.getText());
        if(bb11s.isSelected()){
            select=550.00;
            price=select*qty;
            bb11t.setText(price+"");
        }
        if(bb11m.isSelected()){
            select=850.00;
            price=select*qty;
            bb11t.setText(price+"");
        }
        if(bb11l.isSelected()){
            select=1050.00;
            price=select*qty;
            bb11t.setText(price+"");
        }
    }//GEN-LAST:event_btnb11ActionPerformed

    private void btnb12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnb12ActionPerformed
        // TODO add your handling code here:
        double select,qty=0.0,price;
        qty=Double.parseDouble(bb12q.getText());
        if(bb12s.isSelected()){
            select=550.00;
            price=select*qty;
            bb12t.setText(price+"");
        }
        if(bb12m.isSelected()){
            select=850.00;
            price=select*qty;
            bb12t.setText(price+"");
        }
        if(bb12l.isSelected()){
            select=1050.00;
            price=select*qty;
            bb12t.setText(price+"");
        }
    }//GEN-LAST:event_btnb12ActionPerformed

    private void btnlastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlastActionPerformed
        // TODO add your handling code here:
       try{
           Double a1=0.0;
           Double a2=0.0;
           Double a3=0.0;
           Double a4=0.0;
           Double a5=0.0;
           Double a6=0.0;
           Double a7=0.0;
           Double a8=0.0;
           Double a9=0.0;
           Double a10=0.0;
           Double a11=0.0;
           Double a12=0.0;
           Double answer=0.0;
          //JTextField userInput;
        if(bb1t.getText()!=null && bb1t.getText().length()!=0){
           a1=Double.parseDouble(bb1t.getText()); 
        }  
        if(bb2t.getText()!=null && bb2t.getText().length()!=0){
           a2=Double.parseDouble(bb2t.getText());
        }
        if(bb3t.getText()!=null && bb3t.getText().length()!=0){
           a3=Double.parseDouble(bb3t.getText());
        }
        if(bb4t.getText()!=null && bb4t.getText().length()!=0){
           a4=Double.parseDouble(bb4t.getText());
        }
        if(bb5t.getText()!=null && bb5t.getText().length()!=0){
           a5=Double.parseDouble(bb5t.getText());
        }
        if(bb6t.getText()!=null && bb6t.getText().length()!=0){
           a6=Double.parseDouble(bb6t.getText());
        }
        if(bb7t.getText()!=null && bb7t.getText().length()!=0){
           a7=Double.parseDouble(bb7t.getText());
        }
        if(bb8t.getText()!=null && bb8t.getText().length()!=0){
           a8=Double.parseDouble(bb8t.getText());
        }
        if(bb9t.getText()!=null && bb9t.getText().length()!=0){
           a9=Double.parseDouble(bb9t.getText());
        }
        if(bb10t.getText()!=null && bb10t.getText().length()!=0){
           a10=Double.parseDouble(bb10t.getText());
        }
        if(bb11t.getText()!=null && bb11t.getText().length()!=0){
           a11=Double.parseDouble(bb11t.getText());
        }
        if(bb12t.getText()!=null && bb12t.getText().length()!=0){
           a12=Double.parseDouble(bb12t.getText());
        }
        answer=a1+a2+a3+a4+a5+a6+a7+a8+a9+a10+a11+a12;
        txttotal.setText(answer+"");
        
       }catch(Exception e){
           JOptionPane.showMessageDialog(null, e);
       }
        
    }//GEN-LAST:event_btnlastActionPerformed

    private void txtsearchbillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsearchbillActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtsearchbillActionPerformed

    private void txtsearchbillKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsearchbillKeyReleased
        // TODO add your handling code here:
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/javap","root","");
            String sql="SELECT Number,date,time,item FROM billdetails where number=?";
            PreparedStatement pst=con.prepareStatement(sql);
            pst.setString(1,txtsearchbill.getText());
            ResultSet rs=pst.executeQuery();
            if(rs.next()){
                String setnumber=rs.getString("Number");
                txtnum.setText(setnumber);
                String setdate=rs.getString("date");
                txt_data.setText(setdate);
                String settime=rs.getString("time");
                txttime1.setText(settime);
                String setitem=rs.getString("item");
                txtitem.setText(setitem);
                
            }
            con.close();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        
    }//GEN-LAST:event_txtsearchbillKeyReleased

    private void btninsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btninsertActionPerformed
        // TODO add your handling code here:
         try {
            // TODO add your handling code here:
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/javap","root","");
            String sql="INSERT INTO lastbill(billnum ,date,time,item,total) values(?,?,?,?,?)";
            PreparedStatement pst=con.prepareStatement(sql);
            pst.setString(1, txtnum.getText());
            pst.setString(2, txt_data.getText());
            pst.setString(3, txttime1.getText());
            pst.setString(4, txtitem.getText());
            pst.setString(5, txttotal.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Insert To Record");
            txtnum.setText("");
            txt_data.setText("");
            txttime1.setText("");
            txtitem.setText("");
            txttotal.setText("");
            txtname.setText("");
            txtaddress.setText("");
            txtphone.setText(""); 
            
        } catch (ClassNotFoundException e) {
            JOptionPane.showMessageDialog(null, e);
        } catch (SQLException ex) {
            Logger.getLogger(addworker.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btninsertActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         //SMS sms=new SMS();
          // sms.SendSMS("Bharatah", "gr1234567", "Thank You Business With us.Hogwarts Pizza Team", txtphone.getText(), "https://bulksms.vsms.net/eapi/submission/send_sms/2/2.0");
        //JOptionPane.showMessageDialog(null, "Message Sent!");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
            boolean comlete=txtnum.print();
            boolean comlete1=txt_data.print();
            boolean comlete2=txttime1.print();
            boolean comlete3=txtitem.print();
            boolean comlete4=txttotal.print();
            if(comlete && comlete1 && comlete2 && comlete3 && comlete4){
                JOptionPane.showMessageDialog(null, "Done Printring","Information",JOptionPane.INFORMATION_MESSAGE);
            }
            else{
                JOptionPane.showMessageDialog(null, "Printring","Printer",JOptionPane.ERROR_MESSAGE);
            }
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(lastbill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(lastbill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(lastbill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(lastbill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new lastbill().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton bb10l;
    private javax.swing.JRadioButton bb10m;
    private javax.swing.JTextField bb10q;
    private javax.swing.JRadioButton bb10s;
    private javax.swing.JTextField bb10t;
    private javax.swing.JRadioButton bb11l;
    private javax.swing.JRadioButton bb11m;
    private javax.swing.JTextField bb11q;
    private javax.swing.JRadioButton bb11s;
    private javax.swing.JTextField bb11t;
    private javax.swing.JRadioButton bb12l;
    private javax.swing.JRadioButton bb12m;
    private javax.swing.JTextField bb12q;
    private javax.swing.JRadioButton bb12s;
    private javax.swing.JTextField bb12t;
    private javax.swing.JRadioButton bb1l;
    private javax.swing.JRadioButton bb1m;
    private javax.swing.JTextField bb1q;
    private javax.swing.JRadioButton bb1s;
    private javax.swing.JTextField bb1t;
    private javax.swing.JRadioButton bb2l;
    private javax.swing.JRadioButton bb2m;
    private javax.swing.JTextField bb2q;
    private javax.swing.JRadioButton bb2s;
    private javax.swing.JTextField bb2t;
    private javax.swing.JRadioButton bb3l;
    private javax.swing.JRadioButton bb3m;
    private javax.swing.JTextField bb3q;
    private javax.swing.JRadioButton bb3s;
    private javax.swing.JTextField bb3t;
    private javax.swing.JRadioButton bb4l;
    private javax.swing.JRadioButton bb4m;
    private javax.swing.JTextField bb4q;
    private javax.swing.JRadioButton bb4s;
    private javax.swing.JTextField bb4t;
    private javax.swing.JRadioButton bb5l;
    private javax.swing.JRadioButton bb5m;
    private javax.swing.JTextField bb5q;
    private javax.swing.JRadioButton bb5s;
    private javax.swing.JTextField bb5t;
    private javax.swing.JRadioButton bb6l;
    private javax.swing.JRadioButton bb6m;
    private javax.swing.JTextField bb6q;
    private javax.swing.JRadioButton bb6s;
    private javax.swing.JTextField bb6t;
    private javax.swing.JRadioButton bb7l;
    private javax.swing.JRadioButton bb7m;
    private javax.swing.JTextField bb7q;
    private javax.swing.JRadioButton bb7s;
    private javax.swing.JTextField bb7t;
    private javax.swing.JRadioButton bb8l;
    private javax.swing.JRadioButton bb8m;
    private javax.swing.JTextField bb8q;
    private javax.swing.JRadioButton bb8s;
    private javax.swing.JTextField bb8t;
    private javax.swing.JRadioButton bb9l;
    private javax.swing.JRadioButton bb9m;
    private javax.swing.JTextField bb9q;
    private javax.swing.JRadioButton bb9s;
    private javax.swing.JTextField bb9t;
    private javax.swing.JButton btnb1;
    private javax.swing.JButton btnb10;
    private javax.swing.JButton btnb11;
    private javax.swing.JButton btnb12;
    private javax.swing.JButton btnb2;
    private javax.swing.JButton btnb3;
    private javax.swing.JButton btnb4;
    private javax.swing.JButton btnb5;
    private javax.swing.JButton btnb6;
    private javax.swing.JButton btnb7;
    private javax.swing.JButton btnb8;
    private javax.swing.JButton btnb9;
    private javax.swing.JButton btninsert;
    private javax.swing.JButton btnlast;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField txt_data;
    private javax.swing.JTextField txtaddress;
    private javax.swing.JTextField txtitem;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtnum;
    private javax.swing.JTextField txtphone;
    private javax.swing.JTextField txtsearch;
    private javax.swing.JTextField txtsearchbill;
    private javax.swing.JTextField txttime1;
    private javax.swing.JTextField txttotal;
    // End of variables declaration//GEN-END:variables
}
